// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var gulp, requireDir, tasks;

  gulp = require('gulp');

  requireDir = require('require-dir');

  tasks = requireDir('./task');

  gulp.task('default', ['sync']);

}).call(this);

//# sourceMappingURL=gulpfile.js.map
